export const copy = {
  zh: {
    langLabel: "中文",
    switchLabel: "EN",
    brand: "[Name]",
    railNote: "Public site v1",
    nav: {
      home: "首页",
      about: "关于",
      works: "作品",
      profile: "档案",
      contact: "联系",
    },
    home: {
      kicker: "个人网站 / 公开版",
      title: "[你的名字]",
      intro: "[一句公开定位：你正在做什么、关心什么、希望别人如何认识你]",
      primary: "查看作品",
      secondary: "联系我",
      privacy: "这个版本只放公开信息：作品、经历、能力、联系方式。其余内容默认不进入主页。",
      visual: "[原创头像 / 签名图形]",
    },
    about: {
      kicker: "About",
      title: "公开介绍，不写人设。",
      paragraphs: [
        "[第一段：你希望别人如何理解你的专业方向或兴趣方向。建议 80 字以内。]",
        "[第二段：你正在寻找的机会、合作或长期方向。建议 60 字以内。]",
      ],
      facts: [
        ["Name", "[你的中文名 / English Name]"],
        ["Role", "[公开身份描述，例如：产品 / 研究 / 设计 / 数据]"],
        ["Base", "[城市，可不填]"],
        ["Education", "[学校 / 专业 / 学位，可按公开程度填写]"],
        ["Focus", "[3 个公开方向，用逗号分隔]"],
      ],
    },
    works: {
      kicker: "Works",
      title: "作品区可以先空着，但结构要完整。",
      intro: "每个项目只需要说清楚：背景、你做了什么、结果或下一步。没有成果时，用过程型项目或公开实验占位。",
      image: "[4:3 项目图]",
      cta: "稍后补充详情",
      items: [
        {
          type: "Project 01",
          title: "[项目标题]",
          meta: "[类型 / 时间 / 状态]",
          copy: "[一句话说明它解决了什么问题，避免自夸]",
          palette: "yellow",
        },
        {
          type: "Project 02",
          title: "[课程或研究项目]",
          meta: "[课程 / 研究 / 小组 / 个人]",
          copy: "[你的职责、方法或产出，可留空]",
          palette: "blue",
        },
        {
          type: "Project 03",
          title: "[公开实验]",
          meta: "[prototype / essay / tool]",
          copy: "[一个可以被别人看懂的公开尝试]",
          palette: "green",
        },
        {
          type: "Project 04",
          title: "[未来项目占位]",
          meta: "[coming soon]",
          copy: "[还没准备好时，就保持占位，不编故事]",
          palette: "ink",
        },
      ],
    },
    profile: {
      kicker: "Profile",
      title: "只放可被公开验证的信息。",
      sections: [
        ["Experience", ["[教育经历]", "[实习 / 工作经历]", "[公开活动 / 组织经历]"]],
        ["Capabilities", ["[能力关键词 01]", "[能力关键词 02]", "[能力关键词 03]"]],
        ["Recognition", ["[奖项 / 证书 / 发表，可删除]", "[没有就不放]", "[只保留能被验证的内容]"]],
      ],
    },
    contact: {
      kicker: "Contact",
      title: "让别人知道如何找到你。",
      links: [
        ["Email", "YOUR_EMAIL@example.com", "mailto:YOUR_EMAIL@example.com"],
        ["GitHub", "[github 用户名]", "https://github.com/"],
        ["LinkedIn / Portfolio", "[公开链接，可删除]", "https://www.linkedin.com/"],
      ],
    },
  },
  en: {
    langLabel: "English",
    switchLabel: "中",
    brand: "[Name]",
    railNote: "Public site v1",
    nav: {
      home: "Home",
      about: "About",
      works: "Works",
      profile: "Profile",
      contact: "Contact",
    },
    home: {
      kicker: "Personal Website / Public Version",
      title: "[Your Name]",
      intro: "[One public positioning line: what you do, what you care about, and how people should understand you]",
      primary: "View Works",
      secondary: "Contact",
      privacy: "This version only shows public information: works, experience, capabilities, and contact channels.",
      visual: "[Original portrait / signature graphic]",
    },
    about: {
      kicker: "About",
      title: "A public introduction, not a persona.",
      paragraphs: [
        "[Paragraph 1: how you want people to understand your professional or creative direction. Keep it under 80 words.]",
        "[Paragraph 2: opportunities, collaborations, or long-term directions you are open to. Keep it under 60 words.]",
      ],
      facts: [
        ["Name", "[Chinese Name / English Name]"],
        ["Role", "[Public identity, e.g. product / research / design / data]"],
        ["Base", "[City, optional]"],
        ["Education", "[University / Major / Degree, only if public]"],
        ["Focus", "[3 public directions, comma-separated]"],
      ],
    },
    works: {
      kicker: "Works",
      title: "The work section can be empty, but its structure should be ready.",
      intro: "Each project only needs to explain the context, what you did, and the outcome or next step. Process projects and public experiments are valid placeholders.",
      image: "[4:3 project image]",
      cta: "Details later",
      items: [
        {
          type: "Project 01",
          title: "[Project title]",
          meta: "[Type / Time / Status]",
          copy: "[One sentence about the problem it addresses, without overselling]",
          palette: "yellow",
        },
        {
          type: "Project 02",
          title: "[Course or research project]",
          meta: "[Course / Research / Team / Solo]",
          copy: "[Your role, method, or output; can stay blank]",
          palette: "blue",
        },
        {
          type: "Project 03",
          title: "[Public experiment]",
          meta: "[prototype / essay / tool]",
          copy: "[A public attempt that others can understand]",
          palette: "green",
        },
        {
          type: "Project 04",
          title: "[Future project placeholder]",
          meta: "[coming soon]",
          copy: "[Keep the placeholder when it is not ready. Do not invent a story.]",
          palette: "ink",
        },
      ],
    },
    profile: {
      kicker: "Profile",
      title: "Only show information that can be publicly verified.",
      sections: [
        ["Experience", ["[Education]", "[Internship / Work experience]", "[Public activities / Organizations]"]],
        ["Capabilities", ["[Capability keyword 01]", "[Capability keyword 02]", "[Capability keyword 03]"]],
        ["Recognition", ["[Awards / Certificates / Publications, optional]", "[Remove this section if empty]", "[Keep only verifiable items]"]],
      ],
    },
    contact: {
      kicker: "Contact",
      title: "Make it clear how people can reach you.",
      links: [
        ["Email", "YOUR_EMAIL@example.com", "mailto:YOUR_EMAIL@example.com"],
        ["GitHub", "[github username]", "https://github.com/"],
        ["LinkedIn / Portfolio", "[public link, optional]", "https://www.linkedin.com/"],
      ],
    },
  },
};
